name: 🧪 Unit Tests

on:
  workflow_call:
    inputs:
      godot-bin-name:
        required: true
        type: string

jobs:
  run-unit:
    name: 🧪 Run Unit Tests
    if: |
      !contains(github.event.head_commit.message, '[tests skip]') &&
      !contains(github.event.head_commit.message, '[unit skip]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup SCons
        run: |
          sudo apt-get update
          sudo apt-get install -y scons build-essential

      - name: Import dependency versions
        shell: bash
        run: |
          grep -v '^#' deps.env | grep -v '^$' >> "$GITHUB_ENV"
          GC_VER=$(grep "GODOT_CPP_API_VERSION=" deps.env | cut -d "=" -f 2 | tr -d " ")
          echo "GODOT_CPP_VERSION=$GC_VER" >> "$GITHUB_ENV"

      - name: Fetch godot-cpp
        uses: actions/checkout@v4.2.2
        with:
          repository: godotengine/godot-cpp
          ref: ${{ env.GODOT_CPP_VERSION }}
          path: godot-cpp
          submodules: recursive

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: linux

      - name: Restore SCons Cache
        uses: ./.github/actions/zyris-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache
          cache-name: infra-linux-${{ env.GODOT_VERSION }}

      - name: Restore Test Binaries from Cache
        uses: actions/cache/restore@v4
        with:
          path: dist/
          key: ${{ github.sha }}-test-binaries
          fail-on-cache-miss: true

      - name: Deploy Godot Binary
        run: |
          cp -r dist/godot/* .

      - name: Build with Unit Tests
        shell: bash
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache
        run: |
          scons target=editor platform=linux tests=unit -j$(nproc)

      - name: Setup Environment
        run: |
          BIN_NAME="${{ inputs.godot-bin-name }}"
          chmod +x "$BIN_NAME"
          echo "GODOT_BIN=$(pwd)/$BIN_NAME" >> $GITHUB_ENV

      - name: Run Unit Tests
        run: |
          python utility/tests.py unit
